markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num

blog:
    name: Yinfeng Blog
    description: Be a good dog.
    title: Yinfeng Blog
    url: http://xiao82.com
    duoshuo: xiao82
    tongji: 隐小风
    qiniu: 6197192@qq.com
author:
    name: 隐风
    email: cxfeng1@gmail.com
    weibo: http://weibo.com/619719222
    github: https://github.com/cxfeng1
    logo: http://tp3.sinaimg.cn/2172162082/180/40051799292/1
    douban:
        name: 4431736
        key: 0f096509c5bf36e52d1c2f1d513da4af
